# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DirDB-FTP
version:      0.03
version_from: FTP.pm
installdirs:  site
requires:
    Net::FTP::blat:                0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
